version: "3"
services:
  pg_db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: slack
  backend:
    image: slack-clone
    networks:
      - webnet
    environment:
      DB_HOST: pg_db
      DB_PASS: postgres
      DB_USER: postgres
      DB_NAME: slack
      NODE_ENV: production
      SERVER_URL: http://localhost:3030
    volumes:
      - ./assets:/app/assets
    depends_on:
      - pg_db
  web:
    image: nginx
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template
      - ./assets:/app/assets
    ports:
      - "3030:80"
    networks:
      - webnet
    depends_on:
      - backend
    command:
      /bin/bash -c "cat /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
networks:
  ? webnet
